definitions:
  api.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
info:
  contact: {}
  title: Shipping Service API
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the health status of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
